/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal2;

import java.io.File;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;

/**
 *
 * @author carla
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {
    SMClipPlayer player;
    File f1;
    Clip sound;
    LineListener lineListener;
    ManejadorAudio manejador;
    /**
     * Creates new form VentanaInternaReproductor
     * @param f
     */
    public VentanaInternaReproductor(File f) {
        initComponents();
        player = new SMClipPlayer(f);
      manejador=new ManejadorAudio();
        player.setLineListener(manejador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PlayPressed_48x48.png"))); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/RecordDisabled_48x48.png"))); // NOI18N
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if(player!=null){
            try{
                
                player.play();
//                update(null);
                player.printInfo();
                
           } catch (Exception e) {
            System.err.println(e);
            }
        }
    }//GEN-LAST:event_playActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        if(player!=null) player.stop();
    }//GEN-LAST:event_stopActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton play;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables

    public class ManejadorAudio implements LineListener {

        /**
         * 
         */
        public ManejadorAudio() {
            super();
        }
        String appdata = System.getenv("iconos");
        String playDis = appdata + "\\PlayDisabled_48x48.png";
        File icon = new File(playDis);
        String playPres = appdata + "\\PlayPressed_48x48.png";
        String stopPres = appdata + "\\StopPressedBlue_48x48.png";
        String stopDis = appdata + "\\StopDisabled_48x48.png";
        int time=0;
        
        @Override
        public void update(LineEvent event) {
            
            int length=player.getClip().getFrameLength();
            if (event.getType() == LineEvent.Type.START) {
               
               play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PlayPressed_48x48.png")));
               
               stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/StopDisabled_48x48.png")));
            
            }
            if (event.getType() == LineEvent.Type.STOP) {
      
                play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PlayDisabled_48x48.png")));
                
                stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/StopPressedBlue_48x48.png")));
                //time=player.getClip().getFramePosition();
            }
            if (event.getType() == LineEvent.Type.CLOSE) {
                //TODO
            }
        }

    }

}
